### ISSUE TITLE
laravel passport

### ISSUE THREAD

**Issue by peterbayona** [steverhoades/oauth2-openid-connect-server#15]
Can it be added to laravel passport?

**Comment by steverhoades** [comment]
Unfortunately I don't know enough about how Laravel Passport uses the PHPLeague's OAuth2 Server to answer this question.

**Comment by fgibaux** [comment]
yes it's possible, basically:

redefine the passport service provider:

app/Providers/PassportServiceProvider.php

```
class PassportServiceProvider extends \Laravel\Passport\PassportServiceProvider
{
    /**
     * Make the authorization service instance.
     *
     * @return \League\OAuth2\Server\AuthorizationServer
     */
    public function makeAuthorizationServer()
    {
        $responseType = new IdTokenResponse(new IdentityRepository(), new ClaimExtractor());

        return new AuthorizationServer(
            $this->app->make(\Laravel\Passport\Bridge\ClientRepository::class),
            $this->app->make(\Laravel\Passport\Bridge\AccessTokenRepository::class),
            $this->app->make(\Laravel\Passport\Bridge\ScopeRepository::class),
            $this->makeCryptKey('private'),
            app('encrypter')->getKey(),
            $responseType
        );
    }
}
```
don't forget to load it in you config/app.php

then create a `IdentityRepository` as per the documentation of this package, and make it return your version of a user Entity that implements the proper interface.

**Comment by steverhoades** [comment]
Going to close this issue as it @fgibaux has provided  sufficient answer.

**Comment by ryancwalsh** [comment]
@fgibaux Thanks for the hints. I've been working hard for many hours over multiple days trying to figure this out, but I've been stuck and feel like I should have reached out earlier.

(Looking for a working example, I found https://github.com/fgibaux/Laravel-Passport-API-Server-Client-Demo but don't think you were using `steverhoades/oauth2-openid-connect-server` with Passport there.)

Basically, I have a Laravel site that works great, and I have a new private WordPress site where I want my Laravel users to be able to browse without having to register a WP user. I.e. if they're logged in to my Laravel site, I want to consider them logged-in in WP.

So I have been trying to use this [OpenID Connect plugin](https://wordpress.org/plugins/daggerhart-openid-connect-generic/) on WordPress plus `steverhoades/oauth2-openid-connect-server` on Laravel Passport plus your hints.

After adding various Log commands for debugging, I see that PassportServiceProvider makeAuthorizationServer gets called, then AuthorizationServer completeAuthorizationRequest, then \League\OAuth2\Server\Grant\AuthCodeGrant generates a payload like this:

```
$payload={"client_id":"3","redirect_uri":"https:\/\/m.example.com\/wp-admin\/admin-ajax.php?action=openid-connect-authorize","auth_code_id":"de4f2577895e809472a852aa4a50be67b5901b9eb74cecf0e84048dac31cf87586831ac33350e80d","scopes":[],"user_id":1,"expire_time":"1552639306","code_challenge":null,"code_challenge_method":null}  
```

And then the WordPress plugin says "Invalid token response".

I'd appreciate any suggestions of something to look into. Thanks!

**Comment by fgibaux** [comment]
@ryancwalsh Hi, it's seems a long time I've tinkered with OpenId, it was for a private project I cannot share.
for your error, it appears it's from this line in the wordpress plugin : https://github.com/daggerhart/openid-connect-generic/blob/dev/includes/openid-connect-generic-client.php#L286

looks like there is no id token and/or no bearer token.
I'm not sure but I think I remember the client need to ask for the scope openid for an idToken to be returned.
hope this helps

**Comment by ryancwalsh** [comment]
@fgibaux Thanks so much for your response! I've been making better progress _without_ using Passport and instead using my own custom version of [this use of `\Firebase\JWT\JWT::encode()`](https://github.com/WebDevStudios/aad-first-party-sso-wordpress/tree/master/lib/php-jwt#example) within Laravel and then my own custom version of https://as.wordpress.org/plugins/jwt-authenticator/ as a WordPress plugin. Thanks anyway.

**Comment by diggersworld** [comment]
For anyone visiting this thread, who's struggling to get the ID Token to return, I found I had to implement a custom ScopeRepository that defined the `openid` scope in order to get this work.
