### ISSUE TITLE
Which branch should one use?

### ISSUE THREAD

**Issue by loganto** [steverhoades/oauth2-openid-connect-server#17]
Which branch should one use?    
Packagist lists `0.3` as the latest but seems like `master` branch is ahead of it.    
Is master branch ready to use?

**Comment by rlvillacarlos** [comment]
I have the same concern. The version I got using composer does not have the `ClaimSetInterface` that is required to be implemented by the `UserEntity` class base on the give example.

**Comment by steverhoades** [comment]
Sorry about that. Version 1.0.0 should be available now.

**Comment by loganto** [comment]
Thank you :)
