### ISSUE TITLE
Include the openid scope

### ISSUE THREAD

**Issue by rlvillacarlos** [steverhoades/oauth2-openid-connect-server#18]
I've been trying your library and the example you have given and I found out that somehow I still need to setup the `ScopeRepository` to include the `openid` scope for an openid client to work. 

I think you can either point this out in your example or maybe you can provide a default `ScopeRepository` implementation that automatically include the `openid` scope.

**Comment by steverhoades** [comment]
@rlvillacarlos Sorry for the late response. As much as possible would like to stay away from providing any concrete implementations for a Repository, think single inheritance. I'll give some thought to providing a Trait that could be used by default. 

Thanks so much for the suggestion!
