### ISSUE TITLE
Create new release for current state of master

### ISSUE THREAD

**Issue by jnbeaver** [steverhoades/oauth2-openid-connect-server#24]
Hi there, I was just wondering if you could cut a new tag for the 6 commits since the last release. I was hoping to avoid forking the repo or pointing composer directly at the master branch. Thanks!

**Comment by steverhoades** [comment]
Release v1.1.0 has been tagged.
https://github.com/steverhoades/oauth2-openid-connect-server/releases/tag/v1.1.0
