### ISSUE TITLE
Use JWT\Configuration instead of JWT\Builder

### ISSUE THREAD

**Issue by ronvanderheijden** [steverhoades/oauth2-openid-connect-server#30]
The `lcobucci/jwt` package is upgraded to version 4 in `laravel/passport` via `league/oauth2-server`.

Following the upgrade guide: https://lcobucci-jwt.readthedocs.io/en/latest/upgrading/#v3x-to-v4x

`(new Builder())` should become `$config->builder()`.

**Comment by steverhoades** [comment]
Thanks @ronvanderheijden any chance you can provide a PR?
