### ISSUE TITLE
JWT Version

### ISSUE THREAD

**Issue by quimpm** [steverhoades/oauth2-openid-connect-server#34]
Changes to make it work with new versions of Lcobucci/JWT library

**Comment by Richard87** [comment]
I would also love this... Is there anything I can do to help mov eit along? I see the master does not depend on a specific jwt library anymore (but the tests fails on jwt 4...))

For info:
https://github.com/lcobucci/jwt/issues/714

**Comment by quimpm** [comment]
This will may help you:

[https://lcobucci-jwt.readthedocs.io/en/4.0.0/upgrading/](https://lcobucci-jwt.readthedocs.io/en/4.0.0/upgrading/)
[https://github.com/steverhoades/oauth2-openid-connect-server/pull/33](https://github.com/steverhoades/oauth2-openid-connect-server/pull/33)

This guy fixed the JWT update I think it's based on this project:
[https://github.com/ronvanderheijden/openid-connect](https://github.com/ronvanderheijden/openid-connect)
