### ISSUE TITLE
Example configuration

### ISSUE THREAD

**Issue by taurasOpen** [steverhoades/oauth2-openid-connect-server#4]
Can you please write, where configurations must be made? For example, paths // etc ?

**Comment by steverhoades** [comment]
@taurasOpen I'm not entirely sure I follow your question.  The README specifies the example configuration, this is slightly different than the documentation here: https://oauth2.thephpleague.com/ in which you must pass the IdTokenResponse type to the AuthorizationServer.

**Comment by steverhoades** [comment]
didn't receive a response. closing the issue.
