### ISSUE TITLE
Add support for league/oauth2-server v6.X

### ISSUE THREAD

**Issue by steverhoades** [steverhoades/oauth2-openid-connect-server#5]

**Comment by rmshah989** [comment]
@steverhoades - Any progress on this

**Comment by rmshah989** [comment]
@steverhoades - Thank you for adding the support

**Comment by steverhoades** [comment]
PR #6 has been requested to add this support. As soon as I can get verification this library works with 6.0 i'll get it merged.

**Comment by steverhoades** [comment]
Support has been added with release 0.2.0.
