### ISSUE TITLE
Packagist is not updating composer information

### ISSUE THREAD

**Issue by sgomez** [steverhoades/oauth2-openid-connect-server#9]
Seems like you have a problem with your composer.json and packagist is not updating anymore.

```
bash$ composer validate
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
description : The property description is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
```

You should have more information in your packagist account. If you want to I can send you a PR adding the MIT License and a description.

**Comment by steverhoades** [comment]
Please provide a PR and I’ll get it merged.  Thanks!

**Comment by sgomez** [comment]
Packagists finally updates the metadata. It takes more than usual. Anyway I did the PR. Can you do a tagged version? Thanks!!!

**Comment by steverhoades** [comment]
Tagged v0.3.0 to support version 7.  Thanks for the PR!
